// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBctvnoSr2dxFcouJAD0X0upGsU0crT8sQ',
    appId: '1:1064812754543:web:ac4240ea546ddaaec27f9a',
    messagingSenderId: '1064812754543',
    projectId: 'island-tour-planner-560cc',
    authDomain: 'island-tour-planner-560cc.firebaseapp.com',
    storageBucket: 'island-tour-planner-560cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuYRqQVnq9-oT-haxivnVFTtX0BN3hBnk',
    appId: '1:1064812754543:android:eb3601902a805fb3c27f9a',
    messagingSenderId: '1064812754543',
    projectId: 'island-tour-planner-560cc',
    storageBucket: 'island-tour-planner-560cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlVbPQS1WxRJBxDTLGY7YRiLJ30ap0ruM',
    appId: '1:1064812754543:ios:bf968c2770799332c27f9a',
    messagingSenderId: '1064812754543',
    projectId: 'island-tour-planner-560cc',
    storageBucket: 'island-tour-planner-560cc.appspot.com',
    iosClientId: '1064812754543-sr8mnadhvmjgaov6vjpgu1cnchvlkiij.apps.googleusercontent.com',
    iosBundleId: 'com.example.islandTourPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlVbPQS1WxRJBxDTLGY7YRiLJ30ap0ruM',
    appId: '1:1064812754543:ios:249c61367348e112c27f9a',
    messagingSenderId: '1064812754543',
    projectId: 'island-tour-planner-560cc',
    storageBucket: 'island-tour-planner-560cc.appspot.com',
    iosClientId: '1064812754543-p2s42jqe9ecuek8fomld6qd587slllc0.apps.googleusercontent.com',
    iosBundleId: 'com.example.islandTourPlanner.RunnerTests',
  );
}
